package com.micro.notification.enums;

public enum NotificationType {
    GENERIC,
    ACCOUNT_REGISTRATION,
    EMAIL_VERIFICATION,
    PASSWORD_RESET,
    SOUTENANCE_EVENT,
    SOUTENANCE_SUBMITTED,
    SOUTENANCE_UNDER_REVIEW,
    SOUTENANCE_APPROVED,
    SOUTENANCE_REJECTED,
    SOUTENANCE_AUTHORIZED,
    SOUTENANCE_SCHEDULED,
    SOUTENANCE_JURY_VALIDATED,
    SOUTENANCE_DEFENDED,
    SOUTENANCE_DIRECTOR_APPROVED,
    SOUTENANCE_DIRECTOR_REJECTED,
    SOUTENANCE_RAPPORTEUR_REPORT_SUBMITTED,
    SOUTENANCE_RESULT_SET,
    DURATION_LIMIT_APPROACHING
}
